version: "3.8"

services:
   app:
      image: flow-workflow-builder-frontend:latest
      build:
         context: .
         dockerfile: Dockerfile
      ports:
         - "3000:3000"
      environment:
         - NODE_ENV=production
      # Uncomment and add your environment variables
      # env_file:
      #   - .env.production
      restart: unless-stopped
      # Optional: Add health check
      healthcheck:
         test:
            [
               "CMD",
               "node",
               "-e",
               "require('http').get('http://localhost:3000/api/health', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})",
            ]
         interval: 30s
         timeout: 10s
         retries: 3
         start_period: 40s
